/*
 * This source file was generated by the Gradle 'init' task
 */
package com.craftinginterpreters.lox;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static com.craftinginterpreters.lox.TokenType.*;

import java.util.List;

public class ScannerTest {
    @Test public void scannerCanLexSimple() {
        String source = "var language = \"lox\";";
        LexSimple(source);
    }

    @Test public void scannerCanLexBlockComment(){
        String source = "var /*block comment*/language = \"lox\";";
        LexSimple(source);
    }

    private void LexSimple(String source){
        Scanner scanner = new Scanner(source);

        List<Token> tokens = scanner.scanTokens();
        tokens.forEach(token ->System.out.println(token.toString()));
        assertEquals(6, tokens.size());
        
        Token keywordVar = tokens.get(0);
        Token identifierLang = tokens.get(1);
        Token operatorEqual = tokens.get(2);
        Token stringLox = tokens.get(3);
        Token operatorSemiColon = tokens.get(4);
        Token tokenEOF = tokens.get(5);

        assertEquals(VAR, keywordVar.type);
        assertEquals("var", keywordVar.lexeme);

        assertEquals(IDENTIFIER, identifierLang.type);
        assertEquals("language", identifierLang.lexeme);

        assertEquals(EQUAL, operatorEqual.type);
        assertEquals("=", operatorEqual.lexeme);

        assertEquals(STRING, stringLox.type);
        assertEquals("\"lox\"", stringLox.lexeme);
        assertEquals("lox", stringLox.literal);

        assertEquals(SEMICOLON, operatorSemiColon.type);
        assertEquals(";", operatorSemiColon.lexeme);

        assertEquals(EOF, tokenEOF.type);
        assertEquals("", tokenEOF.lexeme);
    }
}
